### ISSUE TITLE
Modify the Query task to output a JSON file rather than ION

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-surrealdb#10]
### Feature description

Currently, the Query task returns an ION file. However, SurrealDB always returns JSON (in contrast to JDBC Queries that output data in a tabular format that can be stored as rows and columns).

This task should output plain JSON.

See the issue shown in the video:

https://share.descript.com/view/wcXlNE9n3wg

## Reproducer

```yaml
id: aws_event_bridge
namespace: blueprint

tasks:
  - id: send_events
    type: io.kestra.plugin.aws.eventbridge.PutEvents
    entries:
      - source: kestra
        eventBusName: default
        detailType: my-custom-app
        detail:
          message: this could be any event - a user sign-in event or a payment

      - source: kestra
        eventBusName: default
        detailType: my-custom-app
        detail:
          message: this could also be any event - an IoT device event or a sensor reading

      - source: kestra
        eventBusName: default
        detailType: my-custom-app
        detail:
          message: another event which could be a user sign-out event or a newsletter subscription

  - id: working_directory
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: json_payload
        type: io.kestra.core.tasks.storages.LocalFiles
        outputs:
          - "*.json"
        inputs:
          events.json: |
            [
              {
                  "detailType": "my-custom-app",
                  "source": "kestra",
                  "eventBusName": "default",
                  "detail": "{\"message\": \"hello from JSON\"}"
              },
              {
                  "detailType": "my-custom-app",
                  "source": "kestra",
                  "eventBusName": "default",
                  "detail": "{\"message\": \"hello from JSON and Kestra\"}"
              }
            ]

  - id: send_events_defined_in_json
    type: io.kestra.plugin.aws.eventbridge.PutEvents
    entries: "{{outputs.json_payload.uris['events.json']}}"
```
